// Purpose: Curated nationwide tourist places database, hotel directory, emergency service registry, and geo-distance calculator with field masking support for Tamil Nadu and All-India travel.

import type { PlaceSummary, HotelItem, EmergencyServiceItem, PlaceCategory, HelpCategory } from "@/types/place";

/** Calculate distance between two lat/lng points using Haversine formula in kilometers */
export function calculateDistanceKm(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371; // Earth radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

export const CURATED_PLACES: PlaceSummary[] = [
  // ─── OOTY (Nilgiris) ───
  {
    id: "ooty_botanical_gardens",
    displayName: "Government Botanical Garden, Ooty",
    tamilName: "அரசு தாவரவியல் பூங்கா, ஊட்டி",
    formattedAddress: "Vannarapettai, Ooty, Tamil Nadu 643002",
    rating: 4.6,
    userRatingCount: 48200,
    category: "nature",
    city: "Ooty",
    state: "Tamil Nadu",
    location: { latitude: 11.4172, longitude: 76.7118 },
    photoUrl: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800&auto=format&fit=crop&q=80",
    photos: [
      "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
    ],
    description: "Spread over 55 acres on the lower slopes of Doddabetta Peak, featuring over a thousand species of exotic and indigenous flora, fossilized tree trunks, and Italian gardens.",
    highlights: ["Fossil Tree Trunk", "Italian Terrace", "Rare Orchids Glasshouse", "Lush Lawns"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 7:00 AM – 6:30 PM"],
    phoneNumber: "+91 423 244 2235",
  },
  {
    id: "ooty_doddabetta_peak",
    displayName: "Doddabetta Peak",
    tamilName: "தொட்டபெட்டா சிகரம்",
    formattedAddress: "Ooty-Kotagiri Road, Nilgiris, Tamil Nadu 643002",
    rating: 4.5,
    userRatingCount: 36500,
    category: "hills",
    city: "Ooty",
    state: "Tamil Nadu",
    location: { latitude: 11.4011, longitude: 76.7369 },
    photoUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
    description: "The highest mountain in the Nilgiri Mountains at 2,637 meters (8,652 feet), offering breathtaking panoramic views of the Western Ghats and cloud blankets.",
    highlights: ["Telescope House", "Cloud Valley View", "High Altitude Trek", "Tea Plantations"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 9:00 AM – 5:30 PM"],
  },
  {
    id: "ooty_pykara_lake",
    displayName: "Pykara Lake & Waterfalls",
    tamilName: "பைகாரா ஏரி மற்றும் நீர்வீழ்ச்சி",
    formattedAddress: "Pykara, Nilgiris, Tamil Nadu 643237",
    rating: 4.7,
    userRatingCount: 29400,
    category: "waterfalls",
    city: "Ooty",
    state: "Tamil Nadu",
    location: { latitude: 11.4589, longitude: 76.5983 },
    photoUrl: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
    description: "Serene sacred river lake of the Toda community featuring roaring cascading waterfalls, pine forest backdrops, and speedboat cruises.",
    highlights: ["Speedboat Boating", "Cascading Falls", "Pine Forest Walk", "Toda Heritage"],
    priceLevel: "₹₹",
    openingHours: ["Mon - Sun: 8:30 AM – 5:00 PM"],
  },

  // ─── KODAIKANAL ───
  {
    id: "kodai_lake",
    displayName: "Kodaikanal Lake & Coaker's Walk",
    tamilName: "கொடைக்கானல் ஏரி மற்றும் கோக்கர்ஸ் வாக்",
    formattedAddress: "Lake Road, Kodaikanal, Tamil Nadu 624101",
    rating: 4.6,
    userRatingCount: 52000,
    category: "hills",
    city: "Kodaikanal",
    state: "Tamil Nadu",
    location: { latitude: 10.2381, longitude: 77.4892 },
    photoUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
    description: "Star-shaped lake in the heart of the 'Princess of Hill Stations' surrounded by Palani hills. Walk along the scenic Coaker's Walk for mist and valley views.",
    highlights: ["Pedal & Row Boating", "Cycling Ring Road", "Mist Valley Panorama", "Handmade Chocolates"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 6:00 AM – 6:00 PM"],
  },
  {
    id: "kodai_pillar_rocks",
    displayName: "Pillar Rocks & Pine Forest",
    tamilName: "தூண் பாறைகள் மற்றும் பைன் காடு",
    formattedAddress: "Pillar Rocks Road, Kodaikanal, Tamil Nadu 624101",
    rating: 4.5,
    userRatingCount: 27800,
    category: "nature",
    city: "Kodaikanal",
    state: "Tamil Nadu",
    location: { latitude: 10.2078, longitude: 77.4683 },
    photoUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80",
    description: "Three majestic vertical granite boulders standing 122 meters high, flanked by ancient fragrant pine tree forests.",
    highlights: ["122m Granite Pillars", "Centuries Old Pine Woods", "Guna Caves Trail"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 9:00 AM – 4:30 PM"],
  },

  // ─── RAMESHWARAM & DHANUSHKODI ───
  {
    id: "rameshwaram_temple",
    displayName: "Ramanathaswamy Temple & Pamban Bridge",
    tamilName: "ராமநாதசுவாமி திருக்கோயில் & பாம்பன் பாலம்",
    formattedAddress: "Rameswaram, Tamil Nadu 623526",
    rating: 4.8,
    userRatingCount: 64000,
    category: "temples",
    city: "Rameshwaram",
    state: "Tamil Nadu",
    location: { latitude: 9.2881, longitude: 79.3174 },
    photoUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    description: "Historic temple with the world's longest carved pillared corridors (1,212 pillars) and 22 sacred teerthams, beside the cantilever railway over the Indian Ocean.",
    highlights: ["Longest Pillar Corridor", "22 Sacred Wells Bath", "Ocean Cantilever Bridge View"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 5:00 AM – 1:00 PM, 3:00 PM – 9:00 PM"],
  },
  {
    id: "dhanushkodi_beach",
    displayName: "Dhanushkodi Ghost Town & Arichal Munai",
    tamilName: "தனுஷ்கோடி & அரிச்சல் முனை (இந்தியாவின் எல்லை)",
    formattedAddress: "Dhanushkodi Point, Tamil Nadu 623526",
    rating: 4.8,
    userRatingCount: 31200,
    category: "beaches",
    city: "Rameshwaram",
    state: "Tamil Nadu",
    location: { latitude: 9.1517, longitude: 79.4183 },
    photoUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    description: "The southeastern tip of India where the Bay of Bengal meets the Indian Ocean. Submerged ruins of the 1964 cyclone and pristine turquoise beaches.",
    highlights: ["Land's End (Arichal Munai)", "Meeting of Two Oceans", "Submerged Church Ruins"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 6:00 AM – 5:00 PM"],
  },

  // ─── MADURAI ───
  {
    id: "madurai_meenakshi",
    displayName: "Meenakshi Amman Temple",
    tamilName: "மதுரை மீனாட்சி அம்மன் திருக்கோயில்",
    formattedAddress: "Madurai Main, Madurai, Tamil Nadu 625001",
    rating: 4.9,
    userRatingCount: 92000,
    category: "temples",
    city: "Madurai",
    state: "Tamil Nadu",
    location: { latitude: 9.9195, longitude: 78.1193 },
    photoUrl: "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800&auto=format&fit=crop&q=80",
    description: "Iconic Dravidian masterpiece with 14 colorful gopurams, the thousand-pillar hall, and centuries-old spiritual heritage.",
    highlights: ["14 Sculpted Towers", "1000 Pillar Hall", "Golden Lotus Pond", "Jigarthanda Market"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 5:00 AM – 12:30 PM, 4:00 PM – 10:00 PM"],
  },

  // ─── MAHABALIPURAM ───
  {
    id: "mahabalipuram_shore_temple",
    displayName: "Shore Temple & Pancha Rathas",
    tamilName: "கடற்கரை கோயில் மற்றும் பஞ்ச ரதங்கள்",
    formattedAddress: "Beach Road, Mahabalipuram, Tamil Nadu 603104",
    rating: 4.7,
    userRatingCount: 45000,
    category: "heritage",
    city: "Mahabalipuram",
    state: "Tamil Nadu",
    location: { latitude: 12.6163, longitude: 80.1983 },
    photoUrl: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    description: "UNESCO World Heritage 8th-century granite structural temples overlooking the Coromandel Coast with monumental monolithic rock carvings.",
    highlights: ["UNESCO World Heritage", "Monolithic Chariots", "Arjuna's Penance Relief", "Ocean Waves Backdrop"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 6:00 AM – 6:00 PM"],
  },

  // ─── KANYAKUMARI ───
  {
    id: "kanyakumari_memorial",
    displayName: "Vivekananda Rock Memorial & Thiruvalluvar Statue",
    tamilName: "விவேகானந்தர் பாறை & 133 அடி திருவள்ளுவர் சிலை",
    formattedAddress: "Kanyakumari, Tamil Nadu 629702",
    rating: 4.8,
    userRatingCount: 68000,
    category: "heritage",
    city: "Kanyakumari",
    state: "Tamil Nadu",
    location: { latitude: 8.0781, longitude: 77.555 },
    photoUrl: "https://images.unsplash.com/photo-1596405835955-e65fa8c73b4f?w=800&auto=format&fit=crop&q=80",
    description: "Monuments built on twin rock islands where the Arabian Sea, Indian Ocean, and Bay of Bengal unite. Spectacular sunrise and sunset spot.",
    highlights: ["Triveni Sangam", "133-ft Stone Statue", "Ferry Ride Over Waves", "Sunset & Sunrise Point"],
    priceLevel: "₹",
    openingHours: ["Mon - Sun: 8:00 AM – 4:00 PM"],
  },

  // ─── ALL INDIA HIGHLIGHTS ───
  {
    id: "munnar_tea_estates",
    displayName: "Munnar Tea Gardens & Eravikulam",
    tamilName: "மூணார் தேயிலை தோட்டங்கள் & எரவிகுளம்",
    formattedAddress: "Munnar, Kerala 685612",
    rating: 4.8,
    userRatingCount: 54000,
    category: "hills",
    city: "Munnar",
    state: "Kerala",
    location: { latitude: 10.0889, longitude: 77.0595 },
    photoUrl: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
    description: "Rolling carpet of emerald green tea plantations, cool mountain mist, and habitat of the endangered Nilgiri Tahr mountain goat.",
    highlights: ["Nilgiri Tahr Sighting", "Tea Factory Museum", "Anamudi Peak Views", "Mattupetty Dam"],
    priceLevel: "₹₹",
    openingHours: ["Mon - Sun: 7:30 AM – 4:00 PM"],
  },
  {
    id: "goa_palolem_beach",
    displayName: "Palolem Beach & Fort Aguada",
    tamilName: "பாலோலெம் கடற்கரை & அகுவாடா கோட்டை",
    formattedAddress: "Canacona, South Goa, Goa 403702",
    rating: 4.7,
    userRatingCount: 61000,
    category: "beaches",
    city: "Goa",
    state: "Goa",
    location: { latitude: 15.0104, longitude: 74.0232 },
    photoUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
    description: "Crescent-shaped white sand beach lined with swaying coconut palms, beach shacks, and dolphin sightseeing boat trips.",
    highlights: ["Kayaking & Paddleboarding", "Dolphin Watching", "Portuguese Coastal Forts", "Beachfront Dining"],
    priceLevel: "₹₹",
    openingHours: ["Open 24 Hours"],
  },
  {
    id: "jaipur_amber_fort",
    displayName: "Amber Fort & Hawa Mahal",
    tamilName: "அம்பர் கோட்டை & ஹவா மஹால்",
    formattedAddress: "Devisinghpura, Amer, Jaipur, Rajasthan 302001",
    rating: 4.8,
    userRatingCount: 78000,
    category: "heritage",
    city: "Jaipur",
    state: "Rajasthan",
    location: { latitude: 26.9855, longitude: 75.8513 },
    photoUrl: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80",
    description: "Opulent Rajput palace fortress of red sandstone and marble overlooking Maota Lake, famous for its Sheesh Mahal (Mirror Palace).",
    highlights: ["Sheesh Mahal (Mirror Palace)", "Elephant Ride Entry", "Sound & Light Show", "Pink City Bazaars"],
    priceLevel: "₹₹",
    openingHours: ["Mon - Sun: 8:00 AM – 5:30 PM"],
  },
];

export const CURATED_HOTELS: HotelItem[] = [
  {
    id: "hotel_savoy_ooty",
    name: "Savoy - IHCL SeleQtions, Ooty",
    tamilName: "சவோய் ஹோட்டல், ஊட்டி",
    formattedAddress: "77 Sylks Road, Ooty, Tamil Nadu 643001",
    rating: 4.6,
    userRatingCount: 2300,
    priceLevel: "₹₹₹",
    approxNightPaise: 850000, // ₹8,500
    phoneNumber: "+914232225500",
    photoUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80",
    amenities: ["Free Breakfast", "Mountain View", "Fireplace", "Restaurant", "Spa", "Free WiFi"],
    location: { latitude: 11.4115, longitude: 76.7022 },
  },
  {
    id: "hotel_sterling_ooty",
    name: "Sterling Ooty Fern Hill",
    tamilName: "ஸ்டெர்லிங் ஊட்டி ஃபர்ன் ஹில்",
    formattedAddress: "Fern Hill, Ooty, Tamil Nadu 643004",
    rating: 4.4,
    userRatingCount: 3800,
    priceLevel: "₹₹",
    approxNightPaise: 420000, // ₹4,200
    phoneNumber: "+914232443906",
    photoUrl: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&auto=format&fit=crop&q=80",
    amenities: ["Valley View", "Campfire", "Restaurant", "Kids Play Area", "Parking"],
    location: { latitude: 11.3982, longitude: 76.6895 },
  },
  {
    id: "hotel_kodai_resort",
    name: "The Carlton, Kodaikanal",
    tamilName: "தி கார்ல்டன், கொடைக்கானல்",
    formattedAddress: "Lake Road, Kodaikanal, Tamil Nadu 624101",
    rating: 4.7,
    userRatingCount: 4100,
    priceLevel: "₹₹₹",
    approxNightPaise: 920000, // ₹9,200
    phoneNumber: "+914542248555",
    photoUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80",
    amenities: ["Lake View", "Private Lawn", "Jacuzzi", "Buffet Breakfast", "Boating Access"],
    location: { latitude: 10.2372, longitude: 77.4912 },
  },
  {
    id: "hotel_heritage_madurai",
    name: "Heritage Madurai Resort",
    tamilName: "ஹெரிடேஜ் மதுரை ரிசார்ட்",
    formattedAddress: "11 Kochadai, Melakkal Main Road, Madurai 625016",
    rating: 4.6,
    userRatingCount: 5200,
    priceLevel: "₹₹",
    approxNightPaise: 550000, // ₹5,500
    phoneNumber: "+914522385455",
    photoUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop&q=80",
    amenities: ["Temple Architecture Pool", "Banyan Tree Dining", "Free Parking", "Ayurvedic Spa"],
    location: { latitude: 9.9412, longitude: 78.0823 },
  },
];

export const CURATED_EMERGENCY: EmergencyServiceItem[] = [
  // Fuel Stations
  {
    id: "fuel_ioc_ooty",
    category: "fuel",
    name: "Indian Oil Petrol Pump - 24/7",
    tamilName: "இந்தியன் ஆயில் பெட்ரோல் பங்க் (24 மணிநேரம்)",
    address: "Commercial Road, Upper Bazaar, Ooty 643001",
    phoneNumber: "+914232442311",
    isOpenNow: true,
    rating: 4.3,
    location: { latitude: 11.412, longitude: 76.708 },
  },
  {
    id: "fuel_hp_kodai",
    category: "fuel",
    name: "HP Auto Fuel & EV Fast Charger",
    tamilName: "HP பெட்ரோல் & EV சார்ஜிங் நிலையம்",
    address: "Laws Ghat Road, Kodaikanal 624101",
    phoneNumber: "+914542240120",
    isOpenNow: true,
    rating: 4.4,
    location: { latitude: 10.231, longitude: 77.485 },
  },

  // Hospitals & Pharmacies
  {
    id: "hosp_govt_ooty",
    category: "hospital",
    name: "Government District Headquarter Hospital (Emergency 24x7)",
    tamilName: "அரசு தலைமை பொது மருத்துவமனை (24x7 அவசர சிகிச்சை)",
    address: "Hospital Road, Ooty, Tamil Nadu 643001",
    phoneNumber: "+914232442212",
    isOpenNow: true,
    rating: 4.2,
    location: { latitude: 11.4095, longitude: 76.6995 },
  },
  {
    id: "pharm_apollo_ooty",
    category: "pharmacy",
    name: "Apollo Pharmacy 24/7",
    tamilName: "அப்பல்லோ மருந்தகம் (24 மணிநேரம்)",
    address: "Charing Cross, Ooty 643001",
    phoneNumber: "+914232445600",
    isOpenNow: true,
    rating: 4.5,
    location: { latitude: 11.4135, longitude: 76.7125 },
  },

  // ATMs
  {
    id: "atm_sbi_ooty",
    category: "atm",
    name: "State Bank of India 24x7 Cash ATM",
    tamilName: "SBI 24 மணிநேர ஏடிஎம்",
    address: "Charing Cross Road, Ooty 643001",
    phoneNumber: "18001234",
    isOpenNow: true,
    rating: 4.1,
    location: { latitude: 11.414, longitude: 76.711 },
  },

  // Highway Dhabas & Restaurants
  {
    id: "rest_junior_kuppanna",
    category: "restaurant",
    name: "Junior Kuppanna & A2B Veg Highway Hub",
    tamilName: "ஜூனியர் குப்பண்ணா & A2B உணவகம்",
    address: "NH 44 Highway Food Court, Dindigul - Madurai Road",
    phoneNumber: "+919842112233",
    isOpenNow: true,
    rating: 4.6,
    location: { latitude: 10.362, longitude: 77.982 },
  },
];
